# Generated by Django 3.1.2 on 2020-10-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
