# Generated by Django 3.1.2 on 2020-10-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20201019_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='phone',
        ),
    ]
